作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [2]:
#. 將下兩列array存成npz檔
import numpy as np
array1 = np.array(range(30))
array2 = np.array([2,3,5])


In [5]:
with open('mulit_array.npz','wb') as f:
    np.savez(f,array1=array1, array2=array2)

In [6]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
npzfile = np.load('mulit_array.npz')
npzfile.files

['array1', 'array2']

In [7]:
print(npzfile['array1'])
print(npzfile['array2'])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [12]:
x = np.arange(10)
y = np.array([1,2,3])
z = np.random.rand(10)

In [16]:
with open('multi_array_2.npz','wb') as f2:
    np.savez(f2,array1=array1, array2=array2, array3=x, array4=y, array5=z)

In [17]:
npzfile2 = np.load('multi_array_2.npz')
npzfile2.files

['array1', 'array2', 'array3', 'array4', 'array5']

In [19]:
print(npzfile2['array1'])
print(npzfile2['array2'])
print(npzfile2['array3'])
print(npzfile2['array4'])
print(npzfile2['array5'])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.02212212 0.69928975 0.1281612  0.84744376 0.19391404 0.761435
 0.55092612 0.07898359 0.66033669 0.98990621]
