作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [8]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
e_mean = np.mean(english_score)
e_max = np.max(english_score)
e_min = np.min(english_score)
e_std = np.std(english_score)
e_stat = np.array([e_mean, e_max, e_min, e_std]).astype('float16')
e_stat

array([67.2 , 89.  , 48.  , 13.44], dtype=float16)

In [9]:
m_mean = np.nanmean(math_score)
m_max = np.nanmax(math_score)
m_min = np.nanmin(math_score)
m_std = np.nanstd(math_score)
m_stat = np.array([m_mean, m_max, m_min, m_std]).astype('float16')
m_stat

array([66.6 , 85.  , 60.  ,  9.71], dtype=float16)

In [10]:
c_mean = np.mean(chinese_score)
c_max = np.max(chinese_score)
c_min = np.min(chinese_score)
c_std = np.std(chinese_score)
c_stat = np.array([c_mean, c_max, c_min, c_std]).astype('float16')
c_stat

array([75.3 , 90.  , 65.  ,  8.83], dtype=float16)

In [14]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
where_is_nan=np.isnan(math_score)
math_score[where_is_nan] = 55
m_mean = np.nanmean(math_score)
m_max = np.nanmax(math_score)
m_min = np.nanmin(math_score)
m_std = np.nanstd(math_score)
m_stat2 = np.array([m_mean, m_max, m_min, m_std]).astype('float16')
m_stat2

array([63.84 , 85.   , 55.   , 10.414], dtype=float16)

In [19]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
#英文與國文高度相關
a1 = np.array([chinese_score, english_score])
np.corrcoef(a1)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [20]:
a2 = np.array([chinese_score, math_score])
np.corrcoef(a2)

array([[1.       , 0.6860035],
       [0.6860035, 1.       ]])